font_family      JetBrainsMono Nerd Font
font_size        13.0

window_padding_width 12
background_opacity 0.95

cursor_shape beam
cursor_blink_interval 0.5

# Nord colors
background #2E3440
foreground #D8DEE9
cursor     #D8DEE9

# Przewijanie
scrollback_lines 20000

# Clipboard
copy_on_select yes

# Wayland (jeśli jesteś na Waylandzie)
linux_display_server wayland

map ctrl+shift+h launch --stdin-source=@screen_scrollback --type=overlay less -R

tab_bar_style powerline
tab_bar_edge top
tab_bar_align left

active_tab_foreground   #2E3440
active_tab_background   #88C0D0
inactive_tab_foreground #D8DEE9
inactive_tab_background #3B4252

tab_separator "  "
